### ISSUE TITLE
Summary.

### ISSUE THREAD

**Issue by kalverra** [mgdlen/prj-rev-bwfs-dasmoto#6]
**Grade**: Satisfactory

**Summary**:
Overall your code functions well, but make sure to pay attention to how it looks as well. Implementing good coding practices helps others and you read and work on your code much easier. See my comments on general organization, also pay special attention to your indentation. Otherwise, keep it up.

Make sure to check out my link on & codes, they're very important in HTML for representing special characters.

**Comment by mgdlen** [comment]
Thank you for the feedback. I was wondering about the "&" before I put it in but because it didn't go haywire on me I thought it might be ok. 
I don't know where the ".c" came from in my css file - I understand this is incorrect
